In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

TO READ DATA 

In [2]:
df=pd.read_excel(r'C:\Users\Dell Admin\Desktop\BITS\sem-2\machine learning\assignment.xls')

TO REMOVE UNWANTED COLUMNS

In [3]:
df=df.rename(columns={'X1': 'LIMIT_Bal' ,'X2': 'SEX' ,
                      'X3': 'EDUCATION', 'X4': 'MARRIAGE' , 'X5': 'AGE' , 'X6': 'PAY_0' , 'X7': 'PAY_2' ,'X8': 'PAY_3',
                     'X9': 'PAY_4','X10': 'PAY_5','X11': 'PAY_6' , 'X12': 'BILL_amt1','X13': 'BILL_amt2','X14': 'BILL_amt3',
                      'X15': 'BILL_amt4','X16': 'BILL_amt5','X17': 'BILL_amt6' , 'X18' :'PAY_AMT1','X19' :'PAY_AMT2',
                     'X20' :'PAY_AMT3','X21' :'PAY_AMT4','X22' :'PAY_AMT5','X23' :'PAY_AMT6'})


In [4]:
df=df.drop([0],axis=0)
df=df.drop('Unnamed: 0', axis=1)

In [5]:
df = df.fillna(0)

In [6]:
df.columns

Index(['LIMIT_Bal', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0', 'PAY_2',
       'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_amt1', 'BILL_amt2',
       'BILL_amt3', 'BILL_amt4', 'BILL_amt5', 'BILL_amt6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6', 'Y'],
      dtype='object')

SPLITTING OF CATEGORICAL DATA -PREPROCESSING OF DATA

In [7]:
df['grad school']=(df['EDUCATION']==1).astype("int")  

In [8]:
df['university']=(df['EDUCATION']==2).astype("int")

In [9]:
df['high school']=(df['EDUCATION']==3).astype("int")

In [10]:
df.drop('EDUCATION',axis=1,inplace=True)

In [11]:
df['male']=(df['SEX']==1).astype("int")
df['female']=(df['SEX']==2).astype("int")

df.drop('SEX',axis=1,inplace=True)

In [12]:
df['married']=(df['MARRIAGE']==1).astype("int")
df['single']=(df['MARRIAGE']==2).astype("int")

df.drop('MARRIAGE',axis=1,inplace=True)

In [13]:
df = df[['LIMIT_Bal','male','female','grad school' ,'university' ,'high school' ,'married','single' , 'AGE','PAY_0','PAY_2',
         'PAY_3','PAY_4', 'PAY_5', 'PAY_6','BILL_amt1','BILL_amt2','BILL_amt3','BILL_amt4','BILL_amt5','BILL_amt6','PAY_AMT1',
         'PAY_AMT2','PAY_AMT3','PAY_AMT4','PAY_AMT5','PAY_AMT6','Y']]

In [14]:
pay_features=['PAY_0','PAY_2',
         'PAY_3','PAY_4', 'PAY_5', 'PAY_6']
for p in pay_features:
    df.loc[df[p]<=0 , p]=0

# FOR value below 0 , we chnage to 0

In [15]:
df.rename(columns={"Y": "Default"}, inplace=True)

In [16]:
df

LIMIT_Bal  male  female  grad school  university  high school  married  \
1          20000     0       1            0           1            0        1   
2         120000     0       1            0           1            0        0   
3          90000     0       1            0           1            0        0   
4          50000     0       1            0           1            0        1   
5          50000     1       0            0           1            0        1   
...          ...   ...     ...          ...         ...          ...      ...   
29996     220000     1       0            0           0            1        1   
29997     150000     1       0            0           0            1        0   
29998      30000     1       0            0           1            0        0   
29999      80000     1       0            0           0            1        1   
30000      50000     1       0            0           1            0        1   

       single  AGE  PAY_0  ...  BILL_amt4  BILL_amt5  BILL_amt6  PAY_AMT1  \
1           0   24      2  ...          0          0          0         0   
2           1   26      0  ...       3272       3455       3261         0   
3           1   34      0  ...      14331      14948      15549      1518   
4           0   37      0  ...      28314      28959      29547      2000   
5           0   57      0  ...      20940      19146      19131      2000   
...       ...  ...    ...  ...        ...        ...        ...       ...   
29996       0   39      0  ...      88004      31237      15980      8500   
29997       1   43      0  ...       8979       5190          0      1837   
29998       1   37      4  ...      20878      20582      19357         0   
29999       0   41      1  ...      52774      11855      48944     85900   
30000       0   46      0  ...      36535      32428      15313      2078   

       PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  Default  
1           689         0         0         0         0        1  
2          1000      1000      1000         0      2000        1  
3          1500      1000      1000      1000      5000        0  
4          2019      1200      1100      1069      1000        0  
5         36681     10000      9000       689       679        0  
...         ...       ...       ...       ...       ...      ...  
29996     20000      5003      3047      5000      1000        0  
29997      3526      8998       129         0         0        0  
29998         0     22000      4200      2000      3100        1  
29999      3409      1178      1926     52964      1804        1  
30000      1800      1430      1000      1000      1000        1  

[30000 rows x 28 columns]

TO REMOVE UNWANTED COLUMNS

In [17]:
pearsoncorr = df.corr(method='pearson') 

pearsoncorr.head(9)

LIMIT_Bal      male    female  grad school  university  \
LIMIT_Bal     1.000000 -0.024755  0.024755     0.258777   -0.147530   
male         -0.024755  1.000000 -1.000000     0.022750   -0.025353   
female        0.024755 -1.000000  1.000000    -0.022750    0.025353   
grad school   0.258777  0.022750 -0.022750     1.000000   -0.692075   
university   -0.147530 -0.025353  0.025353    -0.692075    1.000000   
high school  -0.139686  0.007650 -0.007650    -0.326917   -0.414989   
married       0.103701 -0.030463  0.030463    -0.153711    0.060923   
single       -0.090998  0.031004 -0.031004     0.164459   -0.059692   
AGE           0.144713  0.090874 -0.090874    -0.100423   -0.077626   

             high school   married    single       AGE     PAY_0  ...  \
LIMIT_Bal      -0.139686  0.103701 -0.090998  0.144713 -0.170745  ...   
male            0.007650 -0.030463  0.031004  0.090874  0.034475  ...   
female         -0.007650  0.030463 -0.031004 -0.090874 -0.034475  ...   
grad school    -0.326917 -0.153711  0.164459 -0.100423 -0.067995  ...   
university     -0.414989  0.060923 -0.059692 -0.077626  0.040454  ...   
high school     1.000000  0.112519 -0.127678  0.231252  0.041765  ...   
married         0.112519  1.000000 -0.975033  0.449425  0.013018  ...   
single         -0.127678 -0.975033  1.000000 -0.466584 -0.013915  ...   
AGE             0.231252  0.449425 -0.466584  1.000000 -0.001447  ...   

             BILL_amt4  BILL_amt5  BILL_amt6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
LIMIT_Bal     0.293988   0.295562   0.290389  0.195236  0.178408  0.210167   
male          0.021880   0.017005   0.016733  0.000242  0.001391  0.008597   
female       -0.021880  -0.017005  -0.016733 -0.000242 -0.001391 -0.008597   
grad school  -0.003809   0.000941  -0.002525  0.049811  0.044400  0.055982   
university    0.021648   0.019690   0.024555 -0.032998 -0.033132 -0.035608   
high school  -0.031276  -0.031708  -0.030981 -0.021310 -0.016674 -0.031726   
married       0.023149   0.025019   0.021169  0.006964  0.011291  0.005339   
single       -0.017708  -0.019356  -0.016064 -0.009039 -0.012598 -0.006216   
AGE           0.051353   0.049345   0.047613  0.026147  0.021785  0.029247   

             PAY_AMT4  PAY_AMT5  PAY_AMT6   Default  
LIMIT_Bal    0.203242  0.217202  0.219595 -0.153520  
male         0.002229  0.001667  0.002766  0.039961  
female      -0.002229 -0.001667 -0.002766 -0.039961  
grad school  0.046119  0.047226  0.050135 -0.051328  
university  -0.026965 -0.021270 -0.026310  0.036467  
high school -0.023554 -0.034768 -0.034613  0.032403  
married      0.014581  0.002195  0.005974  0.029775  
single      -0.014507 -0.001227 -0.003166 -0.030619  
AGE          0.021379  0.022850  0.019478  0.013890  

[9 rows x 28 columns]

Correlation between male n female & married n single is -0.9 and -1 . So need to remove the column

In [18]:
df.drop('female',inplace=True , axis =1)

In [19]:
df.drop('single',inplace=True , axis =1)

In [20]:
df

LIMIT_Bal  male  grad school  university  high school  married  AGE  \
1          20000     0            0           1            0        1   24   
2         120000     0            0           1            0        0   26   
3          90000     0            0           1            0        0   34   
4          50000     0            0           1            0        1   37   
5          50000     1            0           1            0        1   57   
...          ...   ...          ...         ...          ...      ...  ...   
29996     220000     1            0           0            1        1   39   
29997     150000     1            0           0            1        0   43   
29998      30000     1            0           1            0        0   37   
29999      80000     1            0           0            1        1   41   
30000      50000     1            0           1            0        1   46   

       PAY_0  PAY_2  PAY_3  ...  BILL_amt4  BILL_amt5  BILL_amt6  PAY_AMT1  \
1          2      2      0  ...          0          0          0         0   
2          0      2      0  ...       3272       3455       3261         0   
3          0      0      0  ...      14331      14948      15549      1518   
4          0      0      0  ...      28314      28959      29547      2000   
5          0      0      0  ...      20940      19146      19131      2000   
...      ...    ...    ...  ...        ...        ...        ...       ...   
29996      0      0      0  ...      88004      31237      15980      8500   
29997      0      0      0  ...       8979       5190          0      1837   
29998      4      3      2  ...      20878      20582      19357         0   
29999      1      0      0  ...      52774      11855      48944     85900   
30000      0      0      0  ...      36535      32428      15313      2078   

       PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  Default  
1           689         0         0         0         0        1  
2          1000      1000      1000         0      2000        1  
3          1500      1000      1000      1000      5000        0  
4          2019      1200      1100      1069      1000        0  
5         36681     10000      9000       689       679        0  
...         ...       ...       ...       ...       ...      ...  
29996     20000      5003      3047      5000      1000        0  
29997      3526      8998       129         0         0        0  
29998         0     22000      4200      2000      3100        1  
29999      3409      1178      1926     52964      1804        1  
30000      1800      1430      1000      1000      1000        1  

[30000 rows x 26 columns]

STATISTICS OF DATA

In [21]:
df.describe()

LIMIT_Bal          male   grad school    university   high school  \
count    30000.000000  30000.000000  30000.000000  30000.000000  30000.000000   
mean    167484.322667      0.396267      0.352833      0.467667      0.163900   
std     129747.661567      0.489129      0.477859      0.498962      0.370191   
min      10000.000000      0.000000      0.000000      0.000000      0.000000   
25%      50000.000000      0.000000      0.000000      0.000000      0.000000   
50%     140000.000000      0.000000      0.000000      0.000000      0.000000   
75%     240000.000000      1.000000      1.000000      1.000000      0.000000   
max    1000000.000000      1.000000      1.000000      1.000000      1.000000   

            married           AGE         PAY_0         PAY_2         PAY_3  \
count  30000.000000  30000.000000  30000.000000  30000.000000  30000.000000   
mean       0.455300     35.485500      0.356767      0.320033      0.304067   
std        0.498006      9.217904      0.760594      0.801727      0.790589   
min        0.000000     21.000000      0.000000      0.000000      0.000000   
25%        0.000000     28.000000      0.000000      0.000000      0.000000   
50%        0.000000     34.000000      0.000000      0.000000      0.000000   
75%        1.000000     41.000000      0.000000      0.000000      0.000000   
max        1.000000     79.000000      8.000000      8.000000      8.000000   

       ...      BILL_amt4      BILL_amt5      BILL_amt6       PAY_AMT1  \
count  ...   30000.000000   30000.000000   30000.000000   30000.000000   
mean   ...   43262.948967   40311.400967   38871.760400    5663.580500   
std    ...   64332.856134   60797.155770   59554.107537   16563.280354   
min    ... -170000.000000  -81334.000000 -339603.000000       0.000000   
25%    ...    2326.750000    1763.000000    1256.000000    1000.000000   
50%    ...   19052.000000   18104.500000   17071.000000    2100.000000   
75%    ...   54506.000000   50190.500000   49198.250000    5006.000000   
max    ...  891586.000000  927171.000000  961664.000000  873552.000000   

           PAY_AMT2      PAY_AMT3       PAY_AMT4       PAY_AMT5  \
count  3.000000e+04   30000.00000   30000.000000   30000.000000   
mean   5.921163e+03    5225.68150    4826.076867    4799.387633   
std    2.304087e+04   17606.96147   15666.159744   15278.305679   
min    0.000000e+00       0.00000       0.000000       0.000000   
25%    8.330000e+02     390.00000     296.000000     252.500000   
50%    2.009000e+03    1800.00000    1500.000000    1500.000000   
75%    5.000000e+03    4505.00000    4013.250000    4031.500000   
max    1.684259e+06  896040.00000  621000.000000  426529.000000   

            PAY_AMT6       Default  
count   30000.000000  30000.000000  
mean     5215.502567      0.221200  
std     17777.465775      0.415062  
min         0.000000      0.000000  
25%       117.750000      0.000000  
50%      1500.000000      0.000000  
75%      4000.000000      0.000000  
max    528666.000000      1.000000  

[8 rows x 26 columns]

SPLITTING OF DATA SET DEPENDENT AND INDEPENDENT VARIABLE 

In [22]:
X = df.iloc[:, :-1].values
Y = df.iloc[:, -1].values
print(X)
print(Y)

[[ 20000      0      0 ...      0      0      0]
 [120000      0      0 ...   1000      0   2000]
 [ 90000      0      0 ...   1000   1000   5000]
 ...
 [ 30000      1      0 ...   4200   2000   3100]
 [ 80000      1      0 ...   1926  52964   1804]
 [ 50000      1      0 ...   1000   1000   1000]]
[1 1 0 ... 1 1 1]


FEATURE SCALING OF INDEPENDENT VARIABLE

In [23]:
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler


In [24]:
scaler = preprocessing.StandardScaler()
scaled_df = scaler.fit_transform(df.iloc[:, :-1].values)
print(scaled_df)

[[-1.13672015 -0.81016074 -0.73837457 ... -0.30806256 -0.31413612
  -0.29338206]
 [-0.3659805  -0.81016074 -0.73837457 ... -0.24422965 -0.31413612
  -0.18087821]
 [-0.59720239 -0.81016074 -0.73837457 ... -0.24422965 -0.24868274
  -0.01212243]
 ...
 [-1.05964618  1.23432296 -0.73837457 ... -0.03996431 -0.18322937
  -0.11900109]
 [-0.67427636  1.23432296 -0.73837457 ... -0.18512036  3.15253642
  -0.19190359]
 [-0.90549825  1.23432296 -0.73837457 ... -0.24422965 -0.24868274
  -0.23713013]]


SPLITTING OF DATA TO TRAIN N TEST DATA

In [25]:
target=df['Default']
target.head()


1    1
2    1
3    0
4    0
5    0
Name: Default, dtype: int64

In [26]:
from sklearn.model_selection import train_test_split


In [27]:
x_train,x_test,y_train,y_test=train_test_split(scaled_df,target,test_size=0.3,random_state=0)

TRAIN DATA SET USING LOGISTIC REGRESSION AND  PREDICT TEST DATA SET

In [28]:
from sklearn.linear_model import LogisticRegression

In [29]:
model=LogisticRegression(solver='lbfgs').fit(x_train,y_train)
predictions=model.predict(x_test)
print(predictions)


[1 0 0 ... 0 0 0]


CONFUSION MATRIX GENERATION

In [30]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix

confusion_matrix = confusion_matrix(y_test,predictions)
print(confusion_matrix)

[[6783  277]
 [1354  586]]


METRICS CALCULATION

In [31]:
from sklearn.metrics import classification_report
print("Accuracy:",metrics.accuracy_score(y_test,predictions))
print("Precision:",metrics.precision_score(y_test,predictions))
print("Recall:",metrics.recall_score(y_test,predictions))
print(classification_report(y_test,predictions))

Accuracy: 0.8187777777777778
Precision: 0.6790266512166859
Recall: 0.3020618556701031
              precision    recall  f1-score   support

           0       0.83      0.96      0.89      7060
           1       0.68      0.30      0.42      1940

    accuracy                           0.82      9000
   macro avg       0.76      0.63      0.66      9000
weighted avg       0.80      0.82      0.79      9000

